costs <- function(scenario, disc.rate=0)
{
  mdres  <- as.data.frame(apply(attr(scenario, "md_cost"), 2, mean))
  nmdres <- as.data.frame(apply(attr(scenario, "nmd_cost"), 2, mean))
  ires   <- as.data.frame(apply(attr(scenario, "i_cost"), 2, mean))
  res    <- mdres + nmdres + ires
  colnames(mdres)  <- "cost"
  colnames(nmdres) <- "cost"
  colnames(ires)   <- "cost"
  colnames(res)    <- "cost"
  mdres$cost <- mdres$cost/(1+disc.rate/100)^(as.numeric(rownames(mdres))-as.numeric(rownames(mdres))[1])
  nmdres$cost <- nmdres$cost/(1+disc.rate/100)^(as.numeric(rownames(nmdres))-as.numeric(rownames(nmdres))[1])
  ires$cost <- ires$cost/(1+disc.rate/100)^(as.numeric(rownames(ires))-as.numeric(rownames(ires))[1])
  res$cost  <- res$cost/(1+disc.rate/100)^(as.numeric(rownames(res))-as.numeric(rownames(res))[1])
  cat("Total medical cost per strategy\n")
  cat("===============================\n")
  cat(mean(sum(mdres)))
  cat("\n\n")
  cat("Total medical cost per person\n")
  cat("=============================\n")
  cat(mean(sum(mdres))/scenario[1, 1])
  cat("\n\n")
  cat("Total non medical direct cost per strategy\n")
  cat("==========================================\n")
  cat(mean(sum(nmdres)))
  cat("\n\n")
  cat("Total non medical direct cost per person\n")
  cat("========================================\n")
  cat(mean(sum(nmdres))/scenario[1, 1])
  cat("\n\n")
  cat("Total indirect cost per strategy\n")
  cat("================================\n")
  cat(mean(sum(ires)))
  cat("\n\n")
  cat("Total indirect cost per person\n")
  cat("==============================\n")
  cat(mean(sum(ires))/scenario[1, 1])
  cat("\n\n")
  cat("Total cost per strategy\n")
  cat("=======================\n")
  cat(mean(sum(res)))
  cat("\n\n")
  cat("Total cost per person\n")
  cat("=====================\n")
  cat(mean(sum(res))/scenario[1, 1])
  return(c(mean(sum(mdres)), mean(sum(nmdres)), mean(sum(res)), mean(sum(mdres))/scenario[1, 1], mean(sum(nmdres))/scenario[1, 1], mean(sum(res))/scenario[1, 1]))
}